### PR TITLE
[data][xs]: new, larger sample dataset - fixes #29

### LINKED ISSUE #29: Change one dataset to have a lot of points
We want a dataset with a *lot* of points i.e. several thousand.

Suggest we change `day.csv` to be this one. Suggest we can use the gas price data from EIA ;-) (i.e. https://github.com/anuveyatsu/atomatic_task/blob/master/data_daily.csv)

### PR DESCRIPTION
**Pull request by anuveyatsu**
There is a problem with this dataset: it has dates when the price was unavailable, so on this dates it has None value for the price. All libraries handle it, but D3 does not.

So to make D3 work properly, would it be ok to have the same value as the previous day for these dates? E.g.
```
23-11-2010, 3.14
24-11-2010, **None**
25-11-2010, 3.15
```
I want to make 3.14 for 24-11-2010.

### CODE REVIEW

**Comment by rufuspollock** [comment]
@anuveyatsu 

- Any proper dataset would not normally have **None** as avalue. Just delete those rows from the data
- Re time format: can we have iso i.e. `YYYY-MM-DD`

**Comment by rufuspollock** [comment]
@anuveyatsu looking at https://github.com/anuveyatsu/atomatic_task/blob/master/data_daily.csv it had `YYYY-MM-DD` - that's what you should use ;-)

**Comment by anuveyatsu** [comment]
FIXED.

- Date formats are in iso
- Empty records are deleted

**Comment by anuveyatsu** [comment]
is it ok to close issue before you have merged it?

**Comment by rufuspollock** [comment]
@anuveyatsu no - i now can't merge it ;-)

**Comment by rufuspollock** [comment]
But i have re-opened and can now merge 😉

**Pull request merged**
